#!/bin/bash


#SBATCH --job-name=P1                 # Job name
#SBATCH --output=simple%j.out        # Stdout (%j expands to jobId)
#SBATCH --error=adjoint%j.err         # Stderr (%j expands to jobId)
#SBATCH --ntasks=2                  # Total number of tasks
#SBATCH --nodes=2                     # Total number of nodes requested
#SBATCH --ntasks-per-node=1           # Tasks per node
#SBATCH --cpus-per-task=1             # Threads per task(=1) for pure MPI
#SBATCH --mem=500                     # Memory per job in MB
#SBATCH -t 00:04:00                   # Run time (hh:mm:ss) - (max 48h)
#SBATCH --partition=normal           # Submit queue

export PSM3_HAL=loopback

## LOAD MODULES ##
# clean up loaded modules 
source /usr/lib/openfoam/openfoam2312/etc/bashrc

## RUN YOUR PROGRAM ##
mkdir -p runlogs
blockMesh > runlogs/log.blockMesh 2>&1 
decomposePar > runlogs/log.decomposePar 2>&1 
srun simpleFoam -parallel > runlogs/log.simple       2>&1
